version: 1
disable_existing_loggers: False

formatters:
  default:
    format: '[%(asctime)s] #%(levelname)-8s %(filename)s:%(lineno)d - %(name)s:%(funcName)s - %(message)s'

handlers:
  default:
    class: logging.StreamHandler
    formatter: default

  stdout:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

  email:
    class: logging.handlers.SMTPHandler
    mailhost: ['smtp.gmail.com', '587']
    fromaddr: fromaddr@gmail.com
    toaddrs: [ toaddrs@gmail.com ]
    subject: 'GM bot logs'
    credentials: [ 'fromaddr@gmail', 'app-password' ]
    secure: [ ]
    formatter: default

root:
  level: ERROR
  formatter: default
  handlers: [ stdout, email ]
